### ISSUE TITLE
How to use --> add_item_to_template

### ISSUE THREAD

**Issue by lucioaquino** [BrianGallew/zabbix_tool#11]
@BrianGallew  , you made a good job here 

 I have a question  to you 

How to Use   the add_item_to_template , i did not found a answer . 

![image](https://user-images.githubusercontent.com/18651504/35110212-63595cd8-fc5f-11e7-9e5e-24af348348f7.png)

**Comment by BrianGallew** [comment]
It's been 2 years since I've used this script in anger, but the answer is both obvious and annoying: "Takes a template and dictionary of values."  So the first argument is a template (either name or id).  The rest of the arguments look like KEY=VALUE KEY=VALUE KEY=VALUE.  Basically, look at the web form you would use to add an item to a template: you'll want keys/values for every field on there.

Since I'm no longer at the job where I wrote this, I no longer have access to the scripts I used there for creating new templates.

**Comment by lucioaquino** [comment]
Mr Brian , thank you for your time.

I did the tests and even then, I still had problems. Checking out the API documentation, I noticed that there were some parameters required for everything to work.

Thanks again for your attention and for the code. It saves me hours and hours of work.

It´s not my intention to annoying you 

Thank you , very much 



![image](https://user-images.githubusercontent.com/18651504/35152752-c34d7560-fd0a-11e7-9737-165f64d76b34.png)

![image](https://user-images.githubusercontent.com/18651504/35152981-be5de804-fd0b-11e7-9336-eb90d5f4e6ac.png)
